### ISSUE TITLE
The Problem of Shadows

### ISSUE THREAD

**Issue by Boon562** [sixthsurge/photon#20]
![2023-06-21_15 13 46](https://github.com/sixthsurge/photon/assets/137261542/a2ef895d-ba04-4c32-9261-040f202dd9c3)
When I use a 4K monitor and set the shadow distance to 64 chunks it shows up like this. I would like to see this bug fixed.

**Comment by sixthsurge** [comment]
increasing the shadow distance means that the shadow map is stretched over a much larger area, which means that you should increase the shadow map resolution as well. so you need to increase the shadow map resolution too (this problem could also be fixed by increasing the amount of shadow bias but that would cause other problems)

be aware that this is likely to reduce the performance a lot
