### ISSUE TITLE
Optifine versus Iris

### ISSUE THREAD

**Issue by Patomosm** [sixthsurge/photon#28]
Thanks for all the issues fixed so far!

PHOTON is now a better shader than the path-traced ones because it simulates the same results with better performance.

**Too bad for the limitations of Optifine!
To get the same features using Iris (I mean customized entity cem models and connected textures), you need a lot of mods that halve the FPS!**

**Comment by rre36** [comment]
I dont think this is an issue related to the shaderpack, it has nothing to do with the Fabric resourcepack toolset vs OptiFine.
(Also fwiw path-tracing still gives vastly different results than floodfill under these circumstances, so it's not really "simulating the same results", its just broadly trying to achieve the same lighting features.)

**Comment by sixthsurge** [comment]
What she said; my flood-fill lighting looks nowhere near as good as path-tracing, because there are loads of light effects that it just doesn't simulate - shadows, bounced light, etc - which path tracing does. As for OF and Iris, I don't really see how this is an issue with my shader pack (feels a bit like you're trying to subtly encourage me to make the coloured lighting work on OF) so I'm going to close this issue now

**Comment by Patomosm** [comment]
Ok, I didn't think my comment could be offensive. I just wanted to show you my gratitude for the excellent results obtained.
I'm sorry.
