### ISSUE TITLE
The screen will flicker when switch between stained glass and other blocks

### ISSUE THREAD

**Issue by IridescentXs** [sixthsurge/photon#33]
don't know how to solve

**Comment by sixthsurge** [comment]
I know about this but I have no clue why it happens :(

**Comment by Patomosm** [comment]
Some clues I found:

1. It occurs in **first person only**, not in third person;
2. The flicker effect has a **colored flash, that changes** according with sun and moon position in sky: almost white at dawn becoming light blue at noon and blue at dusk; gray at moon dawn getting darker around midnight.
3. May have a connection with issue #25 

Hope I'm helping.

**Comment by Patomosm** [comment]
My guess is that the avatar's hand moves a small portion of the cube through the camera's eye in the first-person view.
The refraction of the glass cube creates the colored flash. With other solid cubes it does not happen because they have no refraction, like air.
If my guess is correct, to solve the problem you should "stretch the avatar's arm" as much as it takes to move the cube away from the camera's eye during swap.

**Comment by sixthsurge** [comment]
fixed in iris
