### ISSUE TITLE
[SUGGESTION] Cumulonimbus clouds, storm systems

### ISSUE THREAD

**Issue by odvigajlo** [sixthsurge/photon#4]
How about adding cumulonimbus clouds?
They can randomly appear during clear skies (but in this case they will only serve decorative purpose)
And they appear during thunder storms.

These clouds should randomly pop up as high tempearture, and high humidity day will pass by.
They should have "anvil shape" and be really big.
Also idk how this can be done but shelf clouds, mammatus clouds, would be great too

Cumulonimbus proggression:
So they should start from small cloud groups starting to rise up, building tall cumulus towers
Then these tall cumulus clouds will form anvil top, at cirrus cloud altitude by "spreading clouds" from tall tower.

**Comment by sixthsurge** [comment]
Hi,

Thanks for the suggestion, cumulonimus clouds are awesome indeed but the problem is that to be able to render such tall clouds the cloud volume has to be much taller, which means a lot more steps through the volume are required to get the same quality result. So unfortunately the performance decrease would not be worth it in my opinion.

If you want a shaderpack that does feature cumulonimbus clouds, you should try [Kappa Shader](https://www.curseforge.com/minecraft/customization/kappa-shader-by-rre36) by RRe36. If you like old Photon (main branch) you'll definitely like this shader too!

**Comment by odvigajlo** [comment]
> Hi,
> 
> Thanks for the suggestion, cumulonimus clouds are awesome indeed but the problem is that to be able to render such tall clouds the cloud volume has to be much taller, which means a lot more steps through the volume are required to get the same quality result. So unfortunately the performance decrease would not be worth it in my opinion.
> 
> If you want a shaderpack that does feature cumulonimbus clouds, you should try [Kappa Shader](https://www.curseforge.com/minecraft/customization/kappa-shader-by-rre36) by RRe36. If you like old Photon (main branch) you'll definitely like this shader too!

Yea i know about Kappa shader, but anvil clouds from Kappa are really strange... If i try to fly trough them, or even fly near they just dissapear or "escape" if possible. and they not tall enough, they cover only 1/4 distance to cirrus clouds. 

How about making experimental branch of shader just to see how they would impact perfomance, and maybe try to adjust settings to find best perfomace with best visuals at same time?

**Comment by sixthsurge** [comment]
I've already tried experimenting with a taller cloud volume and the step count required to keep the quality similar to before was too costly in my opinion. Kappa's cumulonimbus clouds probably don't extend all the way to cirrus layer for the exact reason I told you, having the first cloud volume in Photon extend all the way to the cirrus layer would require it to be more than 11x as tall and 90% of that space would be wasted most of the time.
