### ISSUE TITLE
water reflection

### ISSUE THREAD

**Issue by Spokzooy** [sixthsurge/photon#48]
When the camera moves quickly, the reflection in the water appears too slowly, which is noticeable in the actual game.
[demo.zip](https://github.com/sixthsurge/photon/files/12442644/demo.zip)
![{2C53D364-1A4E-4c1d-A9A2-76584819750C}](https://github.com/sixthsurge/photon/assets/121147347/883d7216-53c1-4af7-b9db-c5e858c85dc3)

1.20.1
Fabric
iris 1.6.8

**Comment by xlifi** [comment]
That's because shader pack is using SSR (Screen Space Reflection) which means that only area being reflected is the area already rendered.
![a](https://github.com/sixthsurge/photon/assets/70767436/f48a5ae7-9eb0-4d97-95c9-59b76e30d809)
Notice how little reflections are rendered compared to the next image. (The image is cut off at the top of my screen)
![b](https://github.com/sixthsurge/photon/assets/70767436/5a641723-2bd1-4c58-b8f4-08040f61f1f7)
<br><br>Only fix is to Ray/Path trace every reflection, but that'll cost you a lot of frames. And I don't think that is the purpose of this shaderpack

**Comment by Spokzooy** [comment]
@xlifi thank you for tell me this.

It looks like Photon doesn't calculate reflected rays outside of the view cone.

Considering I  using chunk render distances greater than 32, I also don't think that's going to be the purpose of this shaderpack.

I understand that there are methods like stretching the reflected image at the edges and interpolating it instead of calculating every light reflection.

This might make the image look better in certain situations (like Elytra flight or open water scenes).

And i don't know if it's easy to implement, maybe it's just my naivety.

**Comment by Patomosm** [comment]
Affects shadows too (trees shadows in bottom video).

https://github.com/sixthsurge/photon/assets/133518090/427b3f65-99d1-42f3-a86a-738af761afd0

I think we shouldn't expect what this shader-pack wasn't designed to do.

**Comment by tsumi666** [comment]
As mentioned, this pack uses screen-space reflections so we have to work within those limits. Stretching reflections may seem like an okay idea in the case of water because of the distortion but it would look strange for 'clean' reflections, not planning on adding this currently.
